/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package teste_api_aluguel;

import java.util.Scanner;

import org.apache.http.Header;
import org.apache.http.HttpEntity;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;
import org.json.JSONObject;

public class App {
    private static final String URL_API_ALUGUEL = "https://aluguebug.herokuapp.com/calc";

    private static String requisicaoGet(String uri, String queryString) throws Exception {
        // Instanciamos o cliente HTTP
        final CloseableHttpClient httpClient = HttpClients.createDefault();

        // Montamos a requisição
        final HttpGet request = new HttpGet(uri + "?" + queryString);

        // Executamos a requisição
        try (CloseableHttpResponse response = httpClient.execute(request)) {

            // Pegamos o status de retorno
            System.out.println("Response Status: " + response.getStatusLine().toString());

            // Pegamos a resposta
            final HttpEntity entity = response.getEntity();
            final Header contentType = entity.getContentType();
            System.out.println(contentType);

            // Se a resposta não for null retornamos a resposta como String.
            if (entity != null) {
                return EntityUtils.toString(entity);
            }

            // Caso a resposta seja null retornamos uma mensagem informativa.
            return "Nenhuma mensagem de retorno.";
        }
    }

    private static String codificaString(String str) {
        // Substituímos os caracteres do objeto que não são aceitos na requisição.
        return str.replace("{", "%7B").replace("}", "%7D").replace("\"", "%22");
    }

    public static String requisicaoAluguel(double valorNominal, int dia) {
        Aluguel objetoAluguel = new Aluguel(valorNominal, dia);
        JSONObject objetoJSONAluguel = new JSONObject(objetoAluguel);
        String stringObjetoJSON = codificaString(objetoJSONAluguel.toString());
        try {
            return requisicaoGet(URL_API_ALUGUEL, "dados=" + stringObjetoJSON);
        } catch (Exception e) {
            return "Erro ao realizar a requisição HTTP! Stacktrace:\n" + e.getStackTrace();
        }
    }

    public static void main(final String[] args) {
        System.out.println("Erica dos Santos Moreira da Rosa\nEsta aplicacao esta consumindo uma API Web.\n");
        Scanner scn = new Scanner(System.in);
        System.out.println("Insira o valor do aluguel:\n");
        double valorNominal = scn.nextDouble();
        System.out.println("Insira o dia de pagamento:\n");
        int dia = scn.nextInt();
        String retornoAPI = requisicaoAluguel(valorNominal, dia);
        System.out.println("\nRetorno da API:\n" + retornoAPI);
        scn.close();
    }
}
