/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package teste_api_aluguel;

import org.junit.Test;
import static org.junit.Assert.*;

// valores_limite_dia = { -1, 0, 1, 5, 6, 10, 11, 15, 16, 30, 31 }

public class AppTest {
    private final double VALOR_NOMINAL = 800.00;

    @Test public void testDiaNegativoESMR() {
        App instanciaApp = new App();
        String retornoAPI = instanciaApp.requisicaoAluguel(VALOR_NOMINAL, -1);
        // Como não existe dia negativo, esperamos um retorno de -1
        assertTrue(retornoAPI.contains("-1"));
    }

    @Test public void testDiaZeroESMR() {
        App instanciaApp = new App();
        String retornoAPI = instanciaApp.requisicaoAluguel(VALOR_NOMINAL, 0);
        // Como não existe dia zero, esperamos um retorno de -1
        assertTrue(retornoAPI.contains("-1"));
    }

    @Test public void testDiaUmESMR() {
        App instanciaApp = new App();
        String retornoAPI = instanciaApp.requisicaoAluguel(VALOR_NOMINAL, 1);
        // Esperamos um desconto de 10%
        assertTrue(retornoAPI.contains("720.0"));
    }

    @Test public void testDiaCincoESMR() {
        App instanciaApp = new App();
        String retornoAPI = instanciaApp.requisicaoAluguel(VALOR_NOMINAL, 5);
        // Esperamos um desconto de 10%
        assertTrue(retornoAPI.contains("720.0"));
    }

    @Test public void testDiaSeisESMR() {
        App instanciaApp = new App();
        String retornoAPI = instanciaApp.requisicaoAluguel(VALOR_NOMINAL, 6);
        // Esperamos um desconto de 5%
        assertTrue(retornoAPI.contains("760.0"));
    }

    @Test public void testDiaDezESMR() {
        App instanciaApp = new App();
        String retornoAPI = instanciaApp.requisicaoAluguel(VALOR_NOMINAL, 10);
        // Esperamos um desconto de 5%
        assertTrue(retornoAPI.contains("760.0"));
    }

    @Test public void testDiaOnzeESMR() {
        App instanciaApp = new App();
        String retornoAPI = instanciaApp.requisicaoAluguel(VALOR_NOMINAL, 11);
        // Esperamos o valor integral (sem desconto)
        assertTrue(retornoAPI.contains("800.0"));
    }

    @Test public void testDiaQuinzeESMR() {
        App instanciaApp = new App();
        String retornoAPI = instanciaApp.requisicaoAluguel(VALOR_NOMINAL, 15);
        // Esperamos o valor integral (sem desconto)
        assertTrue(retornoAPI.contains("800.0"));
    }

    @Test public void testDiaDezesseisESMR() {
        App instanciaApp = new App();
        String retornoAPI = instanciaApp.requisicaoAluguel(VALOR_NOMINAL, 16);
        assertTrue(retornoAPI.contains("816.8"));
    }

    @Test public void testDiaTrintaESMR() {
        App instanciaApp = new App();
        String retornoAPI = instanciaApp.requisicaoAluguel(VALOR_NOMINAL, 30);
        assertTrue(retornoAPI.contains("828.0"));
    }

    @Test public void testDiaTrintaUmESMR() {
        App instanciaApp = new App();
        String retornoAPI = instanciaApp.requisicaoAluguel(VALOR_NOMINAL, 31);
        assertTrue(retornoAPI.contains("-1"));
    }
}
